### ISSUE TITLE
Redesign register page

### ISSUE THREAD

**Issue by Xyli0** [Xyli0/FTracker#1]
The register page /register needs some redesign.
Maybe a nice widget were you can switch between signup and login.

Please use BEM notation: http://getbem.com/introduction/

Feel free to make whatever inspires you.

**Comment by pal-p** [comment]
Hi @Xyli0 , I am interested to contribute to this project. I have a problem running the app, as npm install gives me the error:
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz

Looking for any tips to resolve this please. Thanks

**Comment by Xyli0** [comment]
@pal-p, i have no idea

**Comment by Xyli0** [comment]
Dependencies issue fixed by commit 573c4a597ebb24a759291848b49024a276e1b521

**Comment by pal-p** [comment]
Thank you @Xyli0 for the detailed article. So the malicious event-stream package should be removed from the package-lock.json file. I simply deleted the package-lock.json and run npm install again and everything worked fine.

**Comment by pal-p** [comment]
Can I work on this issue, please

**Comment by Xyli0** [comment]
For sure. Consider it assigned to you...

**Comment by pal-p** [comment]
Thanks

**Comment by NikithaNadig** [comment]
Hey can I work on this?

**Comment by Xyli0** [comment]
@NikithaNadig for sure

**Comment by karanehra** [comment]
@Xyli0 is this still up for grabs?

**Comment by Xyli0** [comment]
@karanehra no
