### ISSUE TITLE
User should not be able to add the same account name multiple times

### ISSUE THREAD

**Issue by Xyli0** [Xyli0/FTracker#6]
Actually a user can create multiple accounts with the same name.
It needs to be fixed.
I made some research and found $addToSet in the mongoose doc
https://docs.mongodb.com/manual/reference/operator/update/addToSet/
The $addToSet operator adds a value to an array unless the value is already present, in which case $addToSet does nothing to that array.
This validator should be used before saving.

**Comment by KingAviator** [comment]
By account name, do you mean user registration or for the accounts model

**Comment by Xyli0** [comment]
For the account model.
User should not be allowed to create a new account if its name already exists.

**Comment by KingAviator** [comment]
Opinion: Why don't we use email, since a user can have a unique email. However a user can have same name as any other user

**Comment by Xyli0** [comment]
No, what i mean is that every account name for a given user should be different. If the user tries to create a new account (account model) with an already existing name it should throw an error like for instance: "You already have an account with the same name"

**Comment by dylanavery720** [comment]
It seems like this has been fixed? 

I tried to create duplicate username and got this error. 

"E11000 duplicate key error index: ftracker_test.users.$username_1 dup key: { : \"earl\" }"

**Comment by Xyli0** [comment]
@dylanavery720 I am not sure but i think this error is telling you that the username you tried to register already exists. What i mean is that one user can't have 2 accounts sharing the same name.
