### ISSUE TITLE
Remove li bulletpoints before accounts

### ISSUE THREAD

**Issue by Xyli0** [Xyli0/FTracker#9]

**Comment by Xyli0** [comment]
Unwanted bulletpoints in dashboard should be removed

**Comment by pal-p** [comment]
Hi @Xyli0, can I work on this issue.
 Thanks

**Comment by Xyli0** [comment]
@pal-p for sure.  You can pack the two issues you are working in the same pull request, that's such a small chance.
Cheers

**Comment by ReenaSingh07** [comment]
can i work on this?

**Comment by KellyStamps** [comment]
hi @Xyli0  - can I work on this issue?
